# Generated by Django 5.2.1 on 2025-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de serie')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('aircraft_type', models.CharField(max_length=50, verbose_name='Tipo de aeronave')),
                ('seating_capacity', models.IntegerField(verbose_name='Capacidad de pasajeros')),
                ('max_takeoff_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso máximo de despegue (kg)')),
                ('empty_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso en vacío (kg)')),
                ('wingspan', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Envergadura (m)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Longitud (m)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Altura (m)')),
                ('max_speed', models.IntegerField(verbose_name='Velocidad máxima (km/h)')),
                ('cruise_speed', models.IntegerField(verbose_name='Velocidad de crucero (km/h)')),
                ('range_km', models.IntegerField(verbose_name='Alcance máximo (km)')),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad de combustible (litros)')),
                ('engine_type', models.CharField(max_length=100, verbose_name='Tipo de motor')),
                ('number_of_engines', models.IntegerField(verbose_name='Número de motores')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Año de fabricación')),
                ('in_service', models.BooleanField(default=True, verbose_name='En servicio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
                'ordering': ['model', 'manufacturer'],
            },
        ),
    ]
